{"name": "se connecter avec des identifiants non valide -- @1.2 ", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {\"method\":\"xpath\",\"selector\":\"//p[text()='Invalid credentials']\"}\n  (Session info: chrome=111.0.5563.64)\nStacktrace:\nBacktrace:\n\t(No symbol) [0x0029DCE3]\n\t(No symbol) [0x002339D1]\n\t(No symbol) [0x00144DA8]\n\t(No symbol) [0x0017019F]\n\t(No symbol) [0x001703AB]\n\t(No symbol) [0x0019EE62]\n\t(No symbol) [0x0018AF14]\n\t(No symbol) [0x0019D57C]\n\t(No symbol) [0x0018ACC6]\n\t(No symbol) [0x00166F68]\n\t(No symbol) [0x001680CD]\n\tGetHandleVerifier [0x00513832+2506274]\n\tGetHandleVerifier [0x00549794+2727300]\n\tGetHandleVerifier [0x0054E36C+2746716]\n\tGetHandleVerifier [0x00346690+617600]\n\t(No symbol) [0x0023C712]\n\t(No symbol) [0x00241FF8]\n\t(No symbol) [0x002420DB]\n\t(No symbol) [0x0024C63B]\n\tBaseThreadInitThunk [0x76486BD9+25]\n\tRtlGetFullPathName_UEx [0x77688FD2+1218]\n\tRtlGetFullPathName_UEx [0x77688F9D+1165]\n\t(No symbol) [0x00000000]\n\n", "trace": "  File \"E:\\BDDprojet2\\venv\\Lib\\site-packages\\behave\\model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"E:\\BDDprojet2\\venv\\Lib\\site-packages\\behave\\matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"features\\steps\\login_orangeHRM_steps.py\", line 24, in saisir_user_pass\n    text_erreur=context.driver.find_element(By.XPATH,\"//p[text()='Invalid credentials']\").text\n                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"E:\\BDDprojet2\\venv\\Lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 830, in find_element\n    return self.execute(Command.FIND_ELEMENT, {\"using\": by, \"value\": value})[\"value\"]\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"E:\\BDDprojet2\\venv\\Lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 440, in execute\n    self.error_handler.check_response(response)\n  File \"E:\\BDDprojet2\\venv\\Lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 245, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "steps": [{"name": "Given ouvrir  application orange sur chrome", "status": "passed", "start": 1678742380540, "stop": 1678742383843}, {"name": "When saisir le nom utlisateur \"Admin\" et mot de passe \"admin123\"", "status": "passed", "start": 1678742383843, "stop": 1678742384387}, {"name": "And cliquer sur le botoun login", "status": "passed", "start": 1678742384387, "stop": 1678742384478}, {"name": "Then valider que le message d erreur s affiche", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {\"method\":\"xpath\",\"selector\":\"//p[text()='Invalid credentials']\"}\n  (Session info: chrome=111.0.5563.64)\nStacktrace:\nBacktrace:\n\t(No symbol) [0x0029DCE3]\n\t(No symbol) [0x002339D1]\n\t(No symbol) [0x00144DA8]\n\t(No symbol) [0x0017019F]\n\t(No symbol) [0x001703AB]\n\t(No symbol) [0x0019EE62]\n\t(No symbol) [0x0018AF14]\n\t(No symbol) [0x0019D57C]\n\t(No symbol) [0x0018ACC6]\n\t(No symbol) [0x00166F68]\n\t(No symbol) [0x001680CD]\n\tGetHandleVerifier [0x00513832+2506274]\n\tGetHandleVerifier [0x00549794+2727300]\n\tGetHandleVerifier [0x0054E36C+2746716]\n\tGetHandleVerifier [0x00346690+617600]\n\t(No symbol) [0x0023C712]\n\t(No symbol) [0x00241FF8]\n\t(No symbol) [0x002420DB]\n\t(No symbol) [0x0024C63B]\n\tBaseThreadInitThunk [0x76486BD9+25]\n\tRtlGetFullPathName_UEx [0x77688FD2+1218]\n\tRtlGetFullPathName_UEx [0x77688F9D+1165]\n\t(No symbol) [0x00000000]\n\n", "trace": "  File \"E:\\BDDprojet2\\venv\\Lib\\site-packages\\behave\\model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"E:\\BDDprojet2\\venv\\Lib\\site-packages\\behave\\matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"features\\steps\\login_orangeHRM_steps.py\", line 24, in saisir_user_pass\n    text_erreur=context.driver.find_element(By.XPATH,\"//p[text()='Invalid credentials']\").text\n                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"E:\\BDDprojet2\\venv\\Lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 830, in find_element\n    return self.execute(Command.FIND_ELEMENT, {\"using\": by, \"value\": value})[\"value\"]\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"E:\\BDDprojet2\\venv\\Lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 440, in execute\n    self.error_handler.check_response(response)\n  File \"E:\\BDDprojet2\\venv\\Lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 245, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "attachments": [{"name": "screenshot", "source": "6d16eaed-555b-44d4-b91c-217ee48e9300-attachment.png", "type": "image/png"}], "start": 1678742384478, "stop": 1678742415650}], "parameters": [{"name": "user", "value": "Admin"}, {"name": "pass", "value": "admin123"}], "start": 1678742375070, "stop": 1678742417913, "uuid": "2355b38a-865c-4551-a365-fa37827a8c8c", "historyId": "a1918ecaa30b80740312596a7c3aaa67", "fullName": "tester la fonctionnalité login de l'application orange HRM: se connecter avec des identifiants non valide", "labels": [{"name": "severity", "value": "normal"}, {"name": "tag", "value": "fonctionnel2"}, {"name": "tag", "value": "smoke"}, {"name": "feature", "value": "tester la fonctionnalité login de l'application orange HRM"}, {"name": "framework", "value": "behave"}, {"name": "language", "value": "cpython3"}]}